spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: sergio
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
